/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mnostva (https://sketchfab.com/mnostva)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/office-room-15-low-poly-3d-model-0402e7c67e0e4a6abc51a7269f59600a
title: Office Room 15 Low-poly 3D model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Room({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Room/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={0.009} position={[.2,-2,-0.2]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert2SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/Room/scene.gltf')
